//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int idDetallePedido { get; set; }
        public int cantidad { get; set; }
        public double descuento { get; set; }
        public decimal precioU { get; set; }
        public decimal precioDesc { get; set; }
        public int idProducto { get; set; }
        public int idPedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
