//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public decimal salario { get; set; }
        public string nss { get; set; }
        public Nullable<bool> estatus { get; set; }
        public int idPersona { get; set; }
        public int idTipoEmpleado { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
