//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int idInventario { get; set; }
        public int idProducto { get; set; }
        public int cantidadMin { get; set; }
        public int cantidadMax { get; set; }
        public int cantidadDisponible { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
