//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Almacen = new HashSet<Almacen>();
            this.DetalleProduccion = new HashSet<DetalleProduccion>();
        }
    
        public int idMaterial { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public Nullable<bool> estatus { get; set; }
        public int idMedida { get; set; }
    
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<DetalleProduccion> DetalleProduccion { get; set; }
        public virtual Medida Medida { get; set; }
    }
}
