//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int idPedido { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string numTarjeta { get; set; }
        public int idUsuario { get; set; }
    
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
