//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idTipoUsuario { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
