//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseniandote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProduccion
    {
        public TipoProduccion()
        {
            this.Produccion = new HashSet<Produccion>();
        }
    
        public int idTipoProduccion { get; set; }
        public string descripcion { get; set; }
        public bool estatus { get; set; }
    
        public virtual ICollection<Produccion> Produccion { get; set; }
    }
}
